# Generated by Django 4.0.3 on 2022-03-16 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cast_api', '0002_casting_casting_vote_character_character_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casting_vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casting_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character_vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
